version: '3'

services:
  node0:
    container_name: prismnode0
    image: "prism/localnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=prism.log
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.2

  node1:
    container_name: prismnode1
    image: "prism/localnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=prism.log
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.3

  node2:
    container_name: prismnode2
    image: "prism/localnode"
    environment:
      - ID=2
      - LOG=prism.log
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.4

  node3:
    container_name: prismnode3
    image: "prism/localnode"
    environment:
      - ID=3
      - LOG=prism.log
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.5

  node4:
    container_name: prismnode4
    image: "prism/localnode"
    environment:
      - ID=4
      - LOG=prism.log
    ports:
      - "26665-26666:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.6

  node5:
    container_name: prismnode5
    image: "prism/localnode"
    environment:
      - ID=5
      - LOG=prism.log
    ports:
      - "26667-26668:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.7

  node6:
    container_name: prismnode6
    image: "prism/localnode"
    environment:
      - ID=6
      - LOG=prism.log
    ports:
      - "26669-26670:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.8

  node7:
    container_name: prismnode7
    image: "prism/localnode"
    environment:
      - ID=7
      - LOG=prism.log
    ports:
      - "26671-26672:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.9

  node8:
    container_name: prismnode8
    image: "prism/localnode"
    environment:
      - ID=8
      - LOG=prism.log
    ports:
      - "26673-26674:26656-26657"
    volumes:
      - ./build:/prism:Z
    networks:
      localnet:
        ipv4_address: 192.165.10.10

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.165.10.0/24

